'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LMSBoard

    '''<summary>
    '''Type_pageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Type_pageTitle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Change_Breadcrumb_PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Change_Breadcrumb_PageTitle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Main_ContentPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Main_ContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
